# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml
analyzer:
  exclude:
    - "flutter_sdk/**"
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - lib/src/resource/l10n/generated/**.dart
    - "flutter_sdk/**"
    - "lib/src/graphql/__generated__/**"
    - "lib/src/graphql/**/__generated__/**"
  errors:
    todo: ignore
    depend_on_referenced_packages: ignore
    sort_pub_dependencies: ignore