targets:
  $default:
    builders:
      freezed:
      # freezedの生成対象を絞って高速化
        generate_for:
          include:
            - lib/src/notifier/**/*state.dart
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: flutter_graphql_sample|lib/src/graphql/schema.graphql
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: flutter_graphql_sample|lib/src/graphql/schema.graphql