name: flutter_graphql_sample
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  device_preview: ^1.0.0
  device_preview_screenshot: ^1.0.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.3
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^1.1.0
  gap: ^2.0.0
  go_router: ^3.0.7
  hooks_riverpod: ^1.0.3
  image: ^3.1.3
  path_provider: ^2.0.9
  shared_preferences: ^2.0.13
  graphql_flutter: ^5.1.0

dev_dependencies:
  build_runner: ^2.1.8
  flutter_gen_runner: ^4.1.6
  # 最新のbuild.gradleの書き方に対応してないので応急処置版を使う
  # https://github.com/fluttercommunity/flutter_launcher_icons/issues/316
  flutter_launcher_icons:
    git:
        url: https://github.com/Davenchy/flutter_launcher_icons.git
        ref: fixMinSdkParseFlutter2.8
  flutter_lints: ^1.0.4
  flutter_native_splash: ^2.1.3+1
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  github: ^9.1.0
  grinder: ^0.9.1
  pedantic_mono: ^1.17.0
  yaml: ^3.1.0
  graphql_codegen: ^0.7.0
  json_serializable: ^6.1.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/

# intlの生成場所を変更
# https://marketplace.visualstudio.com/items?itemName=localizely.flutter-intl#:~:text=Configuration%20options
flutter_intl:
  enabled: true
  class_name: L10n
  main_locale: en
  arb_dir: lib/src/resource/l10n
  output_dir: lib/src/resource/l10n/generated

# flutter_genの生成場所を変更
flutter_gen:
  output: lib/src/resource

flutter_icons:
  android: true
  ios: true